language: node_js
os: linux
dist: xenial

cache: npm

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      script:
        - npm run prettier:check
        - npm run eslint:check
        - npm run typescript:check
        - npm run jest:test
    - stage: deploy
      if:
        - tag IS present
      script: skip
      before_deploy:
        - npm run rollup:build
        - npm run typescript:types
      deploy:
        provider: npm
        skip_cleanup: true
        email: '$NPM_EMAIL'
        api_token: '$NPM_API_TOKEN'
        on:
          tags: true
